### ISSUE TITLE
Error downloading file

### ISSUE THREAD

**Issue by kacperpaluch** [rodriguestiago0/actualbudget-backup#1]
Hi,

I have an error "Error downloading file"

Docker logs:

```
ACTUAL_BUDGET_URL: MyURL
ACTUAL_BUDGET_PASSWORD: *****
ACTUAL_BUDGET_SYNC_ID: MySyncID
========================================
CRON: */1 * * * *
RCLONE_REMOTE: ActualBudgetBackup:Backup/ActualBudgetBackup
RCLONE_GLOBAL_FLAG:
BACKUP_FILE_DATE_FORMAT: %Y-%m-%d-%H-%M (example "[filename].2024-08-27-10-42.zip")
BACKUP_KEEP_DAYS: 0
TIMEZONE: UTC
========================================
running the backup program at 2024-08-27 10:43:00 UTC
ACTUAL_BUDGET_URL: MyURL
ACTUAL_BUDGET_PASSWORD: *****
ACTUAL_BUDGET_SYNC_ID: MySyncID
========================================
CRON: */1 * * * *
RCLONE_REMOTE: ActualBudgetBackup:Backup/ActualBudgetBackup
RCLONE_GLOBAL_FLAG:
BACKUP_FILE_DATE_FORMAT: %Y-%m-%d-%H-%M (example "[filename].2024-08-27-10-43.zip")
BACKUP_KEEP_DAYS: 0
TIMEZONE: UTC
========================================
Downloading Actual Budger backup
Login into Actual Budget
jq: parse error: Invalid numeric literal at line 1, column 10
Get file id for MySyncID
jq: parse error: Invalid numeric literal at line 1, column 10
Downloading backup files
total 12K
drwxr-xr-x    2 root     root        4.0K Aug 27 10:43 .
drwxr-xr-x    1 root     root        4.0K Aug 27 10:43 ..
-rw-r--r--    1 root     root        2.7K Aug 27 10:43 backup.MySyncID.2024-08-27-10-43.zip
Error downloading file
time="2024-08-27T10:43:01Z" level=error msg="error running command: exit status 1" iteration=0 job.command="bash /app/backup.sh" job.position=0 job.schedule="*/1 * * * *"
```

&nbsp;

My docker-compose file:

```
version: '3.4'

services:
  backup:
    image: rodriguestiago0/actualbudget-backup:latest
    restart: always
    container_name: actualbudget-backup
    environment:
        RCLONE_REMOTE_NAME: 'ActualBudgetBackup'
        RCLONE_REMOTE_DIR: 'Backup/ActualBudgetBackup/'
        RCLONE_GLOBAL_FLAG: ''
        ACTUAL_BUDGET_URL: 'MyURL'
        ACTUAL_BUDGET_PASSWORD: 'MyPassword'
        ACTUAL_BUDGET_SYNC_ID: 'MySyncID'
        CRON: '*/1 * * * *'
        BACKUP_FILE_SUFFIX: '%Y-%m-%d-%H-%M'
        BACKUP_KEEP_DAYS: 0
        TIMEZONE: 'UTC'
    volumes:
      - /root/aplikacje/actualbudget-rclone-data:/config/

```
